spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring:
      jpa:
        database-platform: org.hibernate.dialect.H2Dialect
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: create.sql
  codec:
    max-in-memory-size: 500KB

app:
  biance:
    url: https://api.binance.com/api/v3/ticker/bookTicker
  huoBi:
    url: https://api.huobi.pro/market/tickers
